# Generated by Django 4.2 on 2023-04-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_video_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
