# Generated by Django 4.2 on 2023-04-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options_alter_post_author_alter_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'danh mục', 'verbose_name_plural': 'danh mục'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='danh mục'),
        ),
    ]
