# Generated by Django 4.2 on 2023-04-11 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_tag_options_alter_tag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover-category/'),
        ),
        migrations.AddField(
            model_name='tag',
            name='parrent_tag',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.tag', verbose_name='danh mục'),
            preserve_default=False,
        ),
    ]
