# Generated by Django 4.2 on 2023-04-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tag_is_menu_tag_short_name_alter_tag_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='is_menu',
        ),
    ]
