# Generated by Django 4.2 on 2023-04-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_tag_is_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='short_name',
        ),
    ]
