# Generated by Django 4.2 on 2023-04-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_tag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.URLField(blank=True, null=True, verbose_name='id video youtube'),
        ),
    ]
