# Generated by Django 4.2 on 2023-04-12 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_video_video_remove_video_youtube_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='cover',
        ),
    ]
