# Generated by Django 4.2 on 2023-04-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_video_youtube_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'tác giả', 'verbose_name_plural': 'tác giả'},
        ),
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='ảnh đại diện'),
        ),
    ]
