# Generated by Django 4.2 on 2023-04-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tiêu đề')),
                ('cover', models.ImageField(help_text='ảnh slide nên có tỉ lệ cao:rộng là 1:4 để đẹp nhất ', upload_to='slides/', verbose_name='ảnh slide')),
            ],
            options={
                'verbose_name': 'slide trang chủ',
                'verbose_name_plural': 'slide trang chủ',
            },
        ),
    ]
