# Generated by Django 4.2 on 2023-04-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_slide_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(default='banner-e096d064-72d7-40bd-b48d-dd5d13479728', max_length=200, verbose_name='tiêu đề'),
        ),
    ]
