# Generated by Django 4.2 on 2023-04-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_slide_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(default='banner', max_length=200, verbose_name='tiêu đề'),
        ),
    ]
