# Generated by Django 4.2 on 2023-04-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_slide_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='created_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
