# Generated by Django 4.2 on 2023-04-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_post_cover_alter_post_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='ảnh thumbnail'),
        ),
    ]
