# Generated by Django 4.2 on 2023-04-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_remove_tag_slug_alter_tag_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='số lượt like'),
        ),
    ]
