# Generated by Django 4.2 on 2023-04-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_comment_comment_comment_created_time_comment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='id video youtube'),
        ),
        migrations.DeleteModel(
            name='CountView',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
