# Generated by Django 4.2 on 2023-04-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_comment_options_remove_post_youtube_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='dán url video youtube vào đây', max_length=40, null=True, verbose_name='URL video youtube'),
        ),
    ]
