# Generated by Django 4.2 on 2023-04-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'thẻ', 'verbose_name_plural': 'thẻ'},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('van-ban', 'VĂN BẢN'), ('thi-dua', 'THI ĐUA'), ('khen-thuong', 'KHEN THƯỞNG')], max_length=20, verbose_name='danh mục'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='thẻ'),
        ),
    ]
