# Generated by Django 4.2 on 2023-04-17 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_tag_options_alter_post_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
