# Generated by Django 4.2 on 2023-04-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_remove_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'danh mục', 'verbose_name_plural': 'danh mục'},
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='danh mục'),
        ),
    ]
