# Generated by Django 4.2 on 2023-04-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_alter_tag_options_alter_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='trích dẫn')),
                ('author', models.CharField(max_length=50, verbose_name='tác giả')),
            ],
            options={
                'verbose_name': 'trích dẫn',
                'verbose_name_plural': 'trích dẫn',
            },
        ),
    ]
